### PR TITLE
Supports to autoplay video silently

### PR DESCRIPTION
**Pull request by ericeyang**
1. feat: add `muted` parameter and `muted()` method
2. fix useless regular-expression character escape

### CODE REVIEW

**Comment by finngod** [comment]
this player not work views in webview to smartphone android

**Comment by Alex--wu** [comment]
> this player not work views in webview to smartphone android

Hi, please provide us the android phone version, we will check it. :)

**Comment by pandarin12** [comment]
hi bro why my acc not detect in vip audience ?

**Comment by finngod** [comment]
> > this player not work views in webview to smartphone android
> 
> Hi, please provide us the android phone version, we will check it. :)

hi bro, all android version 5.1 to 10.0

**Comment by Alex--wu** [comment]
> > > this player not work views in webview to smartphone android
> > 
> > 
> > Hi, please provide us the android phone version, we will check it. :)
> 
> hi bro, all android version 5.1 to 10.0

Thanks! we will check it ASAP

**Comment by finngod** [comment]
> 
> Thanks! we will check it ASAP

thankyou bro, I'm looking forward to fixing that :)

**Comment by Alex--wu** [comment]
> > Thanks! we will check it ASAP
> 
> thankyou bro, I'm looking forward to fixing that :)

Hi, could you help testing if this fixed your issue?

**Comment by finngod** [comment]
> 
> Hi, could you help testing if this fixed your issue?

not work bro :/
add me discord? FINN#6055 or whatsapp: +55 91 98840-5581
to details in real time

**Comment by finngod** [comment]
and auto mute not work in webview to android bro :/

**Comment by finngod** [comment]
I think what counts the views and the chatbox but it doesn't appear in the webview because Nimo refuses the connection.
https://prnt.sc/w5mnc2
https://prnt.sc/w5mr0p

**Comment by Alex--wu** [comment]
Hi,

About the chatbox, what url are you referring to? Try this url:
https://www.nimo.tv/embed/chat/{roomID}

And about the auto mute not working in webview issue, because of our
internal issue about playerSDK, it won't work until the end of next month,
sorry about that.

**Comment by finngod** [comment]
Hi bro,

auto mute work in webview now but the views not work

**Comment by finngod** [comment]
chat embed is also not showing as views :/

**Comment by Alex--wu** [comment]
Hi, sorry I don't understand, what do you mean about "the views"?

**Comment by finngod** [comment]
https://prnt.sc/wdc560

**Comment by Alex--wu** [comment]
Hi ,
So far , there is no API to fetch the "the views". If the users want to
know the views or the other info, he needs to switch to our website.

I will discuss it with our product manager to see if it is necessary to add
an API for it.

**Comment by finngod** [comment]
> Hi , So far , there is no API to fetch the "the views". If the users want to know the views or the other info, he needs to switch to our website. I will discuss it with our product manager to see if it is necessary to add an API for it.

ok, thanks for answering me.
on twitch this works normally.

**Pull request merged**
